FROM node:18-alpine

WORKDIR /app/frontend

COPY frontend/package*.json ./

RUN npm install
RUN npm install --save-dev @types/node

COPY frontend/ ./

RUN npm run build

CMD ["npx", "vite", "preview", "--host", "0.0.0.0", "--port", "4174"]
